package net.dereva.butler.domain

enum class ServiceType {
    BOTOX,
    DEPILATIONEYEBROWS, DEPILATIONBIKINI, DEPILATIONLEGS,
    HAIRDYEING, HAIRSTYLING, HAIRCUT,
    MAKEUP, MANICURE, MASSAGEBODY, MASSAGEFACIAL,
    PEDICURE, PEELING
}